sonar.projectKey=taller_luitech
sonar.projectName=Taller LuiTech
sonar.organization=jorgelui1987

sonar.sources=app,resources/views,routes,database
sonar.language=php
sonar.php.version=8.1

sonar.exclusions=**/vendor/**,**/node_modules/**,**/storage/**,**/bootstrap/cache/**,**/public/**,**/tests/**,**/database/migrations/**

sonar.sourceEncoding=UTF-8