sonar.projectKey=servicio-tecnico
sonar.projectName=Servicio Tecnico
sonar.organization=jorgelui1987

sonar.sources=app,routes,database,resources/views
sonar.language=php
sonar.php.version=8.1

sonar.exclusions=**/vendor/**,**/node_modules/**,**/storage/**,**/bootstrap/cache/**,**/public/**,**/tests/**,**/database/migrations/**,**/database/factories/**,**/database/seeders/**

sonar.sourceEncoding=UTF-8