sonar.projectKey=taller
sonar.projectName=Servicio Tecnico
sonar.organization=jorgelui1987

sonar.sources=app,routes,database,resources/views
sonar.language=php
sonar.php.version=8.1

# Excluir archivos del framework que no son código de la aplicación
sonar.exclusions=**/vendor/**,**/node_modules/**,**/storage/**,**/bootstrap/**,**/public/**,**/tests/**,**/database/migrations/**,**/database/factories/**,**/database/seeders/**,**/config/**,**/lang/**

sonar.sourceEncoding=UTF-8