upload_max_filesize = 20M
post_max_size = 20M
max_execution_time = 300
memory_limit = 256M
date.timezone = America/Lima

; Seguridad de cookies de sesión
session.cookie_httponly = 1
session.cookie_secure = 1
session.use_strict_mode = 1
session.use_only_cookies = 1